---
functional:
  - Пользователь может зарегистрироваться и войти в аккаунт.
  - Платформа позволяет начать поединок с другим игроком по решению задач.
  - Пользователь может выбрать язык программирования и решать задачи в онлайн-редакторе.
  - Проверка решений осуществляется автоматически по тестам.
  - Есть система рейтинга и отображение статистики игроков.
non-functional:
  - Интерфейс должен быть интуитивно понятным и отзывчивым.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Решения пользователей должны быть изолированы друг от друга (без доступа к чужому коду).
  - Обработка персональных данных должна соответствовать требованиям безопасности (например, хранение паролей в зашифрованном виде).
  - Платформа должна обеспечивать честность игры — невозможность читерства и подмены результатов.
